### ISSUE TITLE
Create validator class

### ISSUE THREAD

**Issue by rubenvecg** [NYCPlanning/db-data-library#106]
So far we check for proper syntax. Build a script that checks for structure and proper field values, including:
- [x] 1. Every field has the right children and right parent nodes
- [x] 4. acl must be either public-read or private
- [x] 6. name must be the same as the file

**Comment by SPTKL** [comment]
@rubenvecg  

2, 3, 5 are not necessary and the assumptions do not always hold true

**Comment by rubenvecg** [comment]
> @rubenvecg
> 
> 2, 3, 5 are not necessary and the assumptions do not always hold true

Oh ok. I removed those 3 from the list. Will the value for version always be "{{ version }} "

**Comment by SPTKL** [comment]
> > @rubenvecg
> > 2, 3, 5 are not necessary and the assumptions do not always hold true
> 
> Oh ok. I removed those 3 from the list. Will the value for version always be "{{ version }} "

no, user should be able to define a version if needed

**Comment by rubenvecg** [comment]
Idea to validate tree structure:

Have a template .yml file that can be passed as an input parameter. It would have all possible fields in the right position. If we can go through each field and populate it using the same indexing from the input file then it is valid. For example, if both `template['dataset']['source']['url']` and `input['dataset']['source']['url']` are not `None` then `url` is on the right part of the file.

`dataset:
   name:
   version:
   acl:
   source:
      url:
         path:
         subpath:
      socrata:
         uid:
         format:`
If config files change in the future, then a new template can be redefined and the class will work with it
