### ISSUE TITLE
Create 2 .yml files for dcp_stateassemblydistricts

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-data-library#192]
We're missing yml files for dcp_stateassemblydistricts and dcp_stateassemblydistricts_wi
Create two new yml files.  Use senateassemblydistricts as an example

**Comment by SashaWeinstein** [comment]
What does `_wi` mean?

**Comment by SashaWeinstein** [comment]
Ah it means "water included." Should have read description in .yml before asking question

**Comment by SashaWeinstein** [comment]
Adopting state senate url but using the state assembly name `nyad` from the arcgis item properties in resource details on the metadata page

**Comment by SashaWeinstein** [comment]
This issue was resolved with [pull request 193](https://github.com/NYCPlanning/db-data-library/pull/193)
