### ISSUE TITLE
versioning in S3 bucket

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-data-library#220]
issue with the versioning tracking in s3 bucket.  

A new folder won't be created matched with the date the update is made and some cases would simply overwritten. This might be expected behavior to avoid create duplicated . But it is not quite explicit how it is done.   

version would come from two places. It would either set by the config templates which is usually a call of `{{version}}` or could be manually set to in the  (see cli.py for details). But it is not quite clear how the default behavior works

**Comment by mbh329** [comment]
@td928 I am not quite sure I understand the issue, would it be possible to walk through an example in person?

**Comment by td928** [comment]
@mbh329  sorry my question is a little ill-phrased and but I think I figured out. When the source is a socrata, there is version parsing mechanism namely`version_socrata` function. 

@SashaWeinstein you pin-pointed where the actions the about where it happened and it is this line 
```python
config = self.parsed_rendered_template(version=self.version_socrata(_uid))
```
 I was looking fo

**Comment by td928** [comment]
I think I should close this and probably just add to the wiki.

**Comment by SashaWeinstein** [comment]
Ok neat. So you were wondering how it gets the date last updated of the socrata dataset to use for the version. and you figured it out. If I'm understanding correctly

**Comment by td928** [comment]
yeah that's exactly right @SashaWeinstein
