### ISSUE TITLE
usdot_airports with new source

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-data-library#230]
usdot_airports source has depreciated with arcgis hub source no longer works https://opendata.arcgis.com/datasets/831853ab8b714a81b6a3e21d0b164a4e_0.geojson

solution: 
[a new potential source is identified](https://adip.faa.gov/agis/public/#/airportSearch/advanced).  Also the downstream exploration on facdb needs to be done for geocoding etc. for this to be fully accepted as the new source.

**Comment by mbh329** [comment]
I think adding to the description already in the yaml template would be good here. The current description is a copy and paste of the data description from the original source but for the engineers I think it would be useful to have a very quick summary of what is actually in the data i.e. "this data contains airports, helicopter pads and seaplane landing areas in nyc which  amount ~20 records"
