### ISSUE TITLE
templates misspelling error 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-data-library#249]
@Oysters1874 made a great catch in trying to debug why the census block isn't being populated but the census tract is for an issue in db-pluto https://github.com/NYCPlanning/db-pluto/issues/315. The templates dcp_cb2020_wi, dcp_ct2010, dcp_cb2020 pass a "STRING_EMPTY_AS_NULL=YES" in the templates but this is an error - the correct argument should be "EMPTY_STRING_AS_NULL=YES". After investigating how many templates follow this convention, I noticed that there were numerous templates that need to be changed:

- [x] dcp_cb2010_wi
- [x] dcp_cb2010
- [x] dcp_cb2020_wi
- [x] dcp_cb2020
- [x] dcp_cdta2020
- [x] dcp_congressionaldistricts
- [x] dcp_nta2010
- [x] dcp_nta2020
- [ ] dcp_ntaboundaries

Not a 100% sure this would be causing a projection issue but this seems to be the only difference in these files when compared to the administrative boundaries that are correctly populating.

**Comment by mbh329** [comment]
All datasets have been updated with the 22a version and checked in QGIS that they are plotting correctly except for dcp_ntaboundaries @NYCPlanning/data-engineering.The dcp_ntaboundaries hasn't been updated in over a year (21c), is this a deprecated dataset @AmandaDoyle?

**Comment by mbh329** [comment]
The last version I was able to successfully get a link for was 21a

**Comment by AmandaDoyle** [comment]
@mbh329  NTAs were supposed to be replaced with CDTAs, but that didn't happen in practice so that's right that the latest is from 21c
