### ISSUE TITLE
The 'latest' folder can contain multiple versions of data

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-data-library#29]
## Issue
Because there are several possible output file formats, it is possible to re-upload data without overwriting it. 
For example:
   + A csv of a given dataset gets upload as version 2021-01-29 and latest.
   + A shapefile of the same dataset gets uploaded as version 2021-02-28 and latest, but no csv gets uploaded as latest.
   + The directory 'latest' now contains data from both 2021-01-29 and 2021-02-28. 

How can we enforce version consistency within "latest?"

## Ideas for solutions

1.  Only use the latest directory for one file format, either consistent across datasets or saved as a "default" in config
2.  Create subdirectories for file type (not ideal)
3.  If the latest option gets called, remove and recreate the latest directory entirely (or keep it and delete everything in it before uploading the new data -- the effect would be the same). In the above example, the 2021-01-29 csv in the latest directory would get deleted when the 2021-02-28 version would get uploaded. The resulting latest directory would only contain shapefile data, and only from 2021-02-28. This approach has the downside that only a single file can exist in latest using our given code, since each output file format is a separate command. 
4.  If upload as latest gets called, remove all files within the latest directory that do not have the same version as the one getting uploaded. We can back-track versions from s3 metadata to do this. This allows us to keep the uploading code as it is, rather than building a "bulk upload" option that iterates through file types.
5. Do not store data in latest. Instead, store metadata documenting which version is latest. We can then use this when loading data to identify which data version to pull.
6. **Remove files of a different version, but only after successfully copying new version files to latest. This way if the copy fails, links don't break.**
     + say we have version A in latest folder
     + we would like to tag B as the latest now
     + make copies to latest using version B
     + scan through latest folder, remove everything that’s not version B
     + done

**Comment by SPTKL** [comment]
1. separate the latest tagging process into a separate function `<class>.tag_latest(version='20210127', ...)` 
2. this function should do the following:
    1. copy files from `.../20210127/` folder into `.../latest/`
    2. store files copied into `files.txt`
    3. or ideally we can store that list of latest files config.yml and config.json

**Comment by SPTKL** [comment]
- A csv of a given dataset gets upload as version 2021-01-29 and tagged as latest
- in latest folder,  file.txt will specify the latest files
```
/ 2021-01-29 /data.csv
``` 
- A shapefile of the same dataset gets uploaded as version 2021-02-28 and tagged as latest, but no csv gets uploaded as latest.
- in latest folder,  file.txt will specify the latest files
```
/ 2021-02-28 /data.shp
```
