### ISSUE TITLE
Create yml config files for six datasets

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-data-library#51]
- [x] dpr_parksproperties

Bytes:
- [x] dcp_colp

OpenData:
- [x] doitt_buildingfootprints
- [x] doitt_buildingfootprints_historical
- [x] nycha_communitycenters
- [x] nycha_policeservice
- [x] dcla_culturalinstitutions

**Comment by rubenvecg** [comment]
What are the possible values for the acl field? How do I know which one is it for a particular dataset?

**Comment by SPTKL** [comment]
the other option is `private`, public sourced datasets should remain public
