### ISSUE TITLE
Create config files for census blocks

### ISSUE THREAD

**Issue by rubenvecg** [NYCPlanning/db-data-library#84]
dcp_censusblocks and dcp_censusblocks_wi .yml files.

**Comment by rubenvecg** [comment]
@mgraber @SPTKL  Should I source from https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_Census_Blocks_for_2010_US_census_Water_Included/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson

or from https://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page

**Comment by mgraber** [comment]
@rubenvecg Take it from the second. For example, https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nycb2010_20d.zip for the shapefile of the 20d version.
